services:
  auction.webapi:
    image: api
    container_name: auction-webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://auction.dashboard:18889
      - ConnectionStrings__Default=Host=auction.db;Port=5432;Database=auctiondb;Username=auctionuser;Password=auctionpass
    depends_on:
      - auction.db
    networks:
      - auction-network

  auction.dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    container_name: dashboard
    ports:
      - "18888:18888"
    networks:
      - auction-network

  auction.db:
    image: postgres:16
    container_name: auction-db
    restart: always
    environment:
      POSTGRES_DB: auctiondb
      POSTGRES_USER: auctionuser
      POSTGRES_PASSWORD: auctionpass
    ports:
      - "5432:5432"
    volumes:
      - auction-db-data:/var/lib/postgresql/data
    networks:
      - auction-network

networks:
  auction-network:
    driver: bridge

volumes:
  auction-db-data: